#!/bin/bash

# Manual Screenshot Capture Process for Romanian Septica
# This script provides step-by-step instructions for manual screenshot capture

echo "🇷🇴 Romanian Septica Manual Screenshot Capture Process"
echo "======================================================"
echo ""
echo "This guide will walk you through manually capturing screenshots using Xcode"
echo "for the best quality and control over the Romanian cultural presentation."
echo ""

# Romanian flag colors for reference
ROMANIAN_BLUE="#004C9F"
ROMANIAN_YELLOW="#FCD535" 
ROMANIAN_RED="#CE1126"

echo "📋 Manual Capture Steps:"
echo ""
echo "1. 📱 DEVICE SETUP"
echo "   Open Xcode → Window → Devices and Simulators"
echo "   Create/select these simulators:"
echo "   • iPhone 16 Pro Max (6.7\" - 1290x2796)"
echo "   • iPhone 16 Plus (6.5\" - 1242x2688)" 
echo "   • iPhone 16 (5.5\" - 1242x2208)"
echo "   • iPad Pro 13-inch (12.9\" - 2048x2732)"
echo "   • iPad Pro 11-inch (11.0\" - 1668x2388)"
echo ""

echo "2. 🚀 APP LAUNCH"
echo "   In Xcode:"
echo "   • Select target device from dropdown"
echo "   • Click ▶️ Run button"
echo "   • Wait for app to launch on simulator"
echo ""

echo "3. 📸 SCREENSHOT CAPTURE"
echo "   For each device size, capture these 6 screenshots:"
echo ""

echo "   Screenshot 1: Main Menu"
echo "   • Navigate to: App launch (main menu)"
echo "   • Ensure: Romanian title 'SEPTICA' is visible"
echo "   • Ensure: Subtitle 'Jocul Tradițional Românesc' is visible"
echo "   • Ensure: Card symbols (♠♦♣♥) are displayed"
echo "   • Ensure: Romanian flag colors are prominent"
echo "   • Capture: Device → Screenshot (Cmd+S) or iOS Simulator → Device → Screenshot"
echo "   • Save as: iPhone_6.7/Raw/01_main_menu.png"
echo ""

echo "   Screenshot 2: Gameplay" 
echo "   • Navigate to: Tap 'New Game' → Start game"
echo "   • Wait for: Cards to be dealt"
echo "   • Look for: A 7 card visible (wild card)"
echo "   • Ensure: Game table is visible with Romanian styling"
echo "   • Ensure: Player and opponent hands are shown"
echo "   • Capture and save as: iPhone_6.7/Raw/02_gameplay.png"
echo ""

echo "   Screenshot 3: Settings/Accessibility"
echo "   • Navigate to: Main Menu → Settings"
echo "   • Open: Accessibility section" 
echo "   • Ensure: VoiceOver options are visible"
echo "   • Ensure: Romanian cultural respect in design"
echo "   • Capture and save as: iPhone_6.7/Raw/03_accessibility.png"
echo ""

echo "   Screenshot 4: Rules/Cultural Heritage"
echo "   • Navigate to: Main Menu → How to Play"
echo "   • Ensure: Romanian rules are displayed"
echo "   • Ensure: Cultural heritage information is visible"
echo "   • Ensure: Traditional elements are prominent"
echo "   • Capture and save as: iPhone_6.7/Raw/04_cultural_heritage.png"
echo ""

echo "   Screenshot 5: Statistics"
echo "   • Navigate to: Main Menu → Statistics" 
echo "   • Ensure: Game progress is displayed"
echo "   • Ensure: Romanian cultural elements in design"
echo "   • Capture and save as: iPhone_6.7/Raw/05_statistics.png"
echo ""

echo "   Screenshot 6: Game Result/Victory"
echo "   • Play a game to completion OR"
echo "   • Navigate to: Previous game results"
echo "   • Ensure: Victory/result screen is shown"
echo "   • Ensure: Romanian celebration elements visible"
echo "   • Capture and save as: iPhone_6.7/Raw/06_victory.png"
echo ""

echo "4. 🔄 REPEAT FOR ALL DEVICES"
echo "   Repeat steps 2-3 for each device:"
echo "   • iPhone_6.7/ (iPhone 16 Pro Max)"
echo "   • iPhone_6.5/ (iPhone 16 Plus)"  
echo "   • iPhone_5.5/ (iPhone 16)"
echo "   • iPad_12.9/ (iPad Pro 13-inch)"
echo "   • iPad_11.0/ (iPad Pro 11-inch)"
echo ""

echo "5. ✨ POST-PROCESSING"
echo "   After capturing all raw screenshots:"
echo "   • Run: ./add_overlays.sh"
echo "   • This will add Romanian cultural text overlays"
echo "   • Review processed images in /Processed/ folders"
echo ""

echo "📁 Expected Directory Structure After Capture:"
echo "AppStoreScreenshots/"
echo "├── iPhone_6.7/Raw/ (6 screenshots)"
echo "├── iPhone_6.5/Raw/ (6 screenshots)"
echo "├── iPhone_5.5/Raw/ (6 screenshots)" 
echo "├── iPad_12.9/Raw/ (6 screenshots)"
echo "├── iPad_11.0/Raw/ (6 screenshots)"
echo "└── Total: 30 raw screenshots"
echo ""

echo "🎨 Romanian Cultural Elements to Verify:"
echo "• Colors: Blue ($ROMANIAN_BLUE), Yellow ($ROMANIAN_YELLOW), Red ($ROMANIAN_RED)"
echo "• Text: 'Septica Românească', 'Jocul Tradițional Românesc'"
echo "• Symbols: Traditional Romanian card symbols"
echo "• Design: Folk art influences and cultural patterns"
echo ""

echo "🚀 Ready to begin manual capture!"
echo "Open Xcode and start with iPhone 16 Pro Max simulator."
echo ""
echo "📞 Need help? Check SCREENSHOT_CAPTURE_GUIDE.md for detailed instructions."