apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: septica-psp
  namespace: septica
  labels:
    app.kubernetes.io/name: romanian-septica
    app.kubernetes.io/component: security
spec:
  privileged: false
  allowPrivilegeEscalation: false
  requiredDropCapabilities:
    - ALL
  allowedCapabilities:
    - NET_BIND_SERVICE
  volumes:
    - 'configMap'
    - 'emptyDir'
    - 'projected'
    - 'secret'
    - 'downwardAPI'
    - 'persistentVolumeClaim'
  hostNetwork: false
  hostIPC: false
  hostPID: false
  runAsUser:
    rule: 'MustRunAsNonRoot'
  supplementalGroups:
    rule: 'MustRunAs'
    ranges:
      - min: 1001
        max: 65535
  fsGroup:
    rule: 'MustRunAs'
    ranges:
      - min: 1001
        max: 65535
  readOnlyRootFilesystem: true
  seLinux:
    rule: 'RunAsAny'

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: septica-psp-user
  namespace: septica

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: septica-psp-user
  namespace: septica
rules:
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  verbs:
  - use
  resourceNames:
  - septica-psp

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: septica-psp-user
  namespace: septica
roleRef:
  kind: Role
  name: septica-psp-user
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: septica-psp-user
  namespace: septica