apiVersion: v1
kind: Namespace
metadata:
  name: septica
  labels:
    name: septica
    app.kubernetes.io/name: romanian-septica
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: namespace
---
apiVersion: v1
kind: Namespace
metadata:
  name: septica-staging
  labels:
    name: septica-staging
    app.kubernetes.io/name: romanian-septica
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: namespace
    environment: staging